version: '3.7'

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080
    environment:
      - ADMINER_DEFAULT_SERVER=postgres:5432
      - ADMINER_PLUGINS=enum-types enum-option json-column
    networks:
      - tsuwari-dev

  postgres:
    restart: unless-stopped
    image: postgres:14-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: tsuwari
      POSTGRES_PASSWORD: tsuwari
      POSTGRES_DB: tsuwari
    ports:
      - 57453:5432
    networks:
      - tsuwari-dev

  redis:
    restart: unless-stopped
    image: redis/redis-stack:latest
    volumes:
      - redis-data:/data
    ports:
      - 62510:6379
    networks:
      - tsuwari-dev

volumes:
  redis-data:
  postgres-data:

networks:
  tsuwari-dev:
    name: tsuwari-dev
