version: "3.9"

services:
  adminer:
    image: adminer
    environment:
      - ADMINER_PLUGINS=enum-types
    networks:
      - twir
      - traefik-public
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.twir-adminer.rule=Host(`adminer.twir.app`)
        - traefik.http.routers.twir-adminer.middlewares=admin-auth
        - traefik.http.services.twir-adminer.loadbalancer.server.port=8080
        - traefik.docker.network=traefik-public

  postgres:
    image: postgres:14-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./configs/postgres.conf:/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_USER_FILE: /run/secrets/twir_postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/twir_postgres_password
      POSTGRES_DB_FILE: /run/secrets/twir_postgres_db
    secrets:
      - twir_postgres_user
      - twir_postgres_password
      - twir_postgres_db
    networks:
      - twir
    deploy:
      restart_policy:
        condition: any
        delay: 30s
        max_attempts: 30
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.role == manager

  postgres-backup:
    build:
      context: .
      dockerfile: ./tools/pg-backup/Dockerfile
    image: registry.satont.ru/twir/postgres-backup:latest
    secrets:
      - twir_doppler_token
    networks:
      - twir
    deploy:
      restart_policy:
        condition: any
        delay: 30s
        max_attempts: 30
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.role == manager

  migrations:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: migrations
    image: registry.satont.ru/twir/migrations:latest
    secrets:
      - twir_doppler_token
    networks:
      - twir
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 30
    healthcheck:
      test: "exit 0"

  redis:
    image: bitnami/redis:latest
    volumes:
      - redis-data:/bitnami/redis/data
    networks:
      - twir
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    command: /opt/bitnami/scripts/redis/run.sh --protected-mode no
    deploy:
      restart_policy:
        condition: any
        delay: 3s
        max_attempts: 30
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.role == manager

  api:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: api
    image: registry.satont.ru/twir/api:latest
    secrets:
      - twir_doppler_token
    networks:
      - twir
      - traefik-public
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.twir-api.rule=Host(`twir.app`) && PathPrefix(`/api`)
        - traefik.http.routers.twir-api.middlewares=api-stripprefix
        - traefik.http.middlewares.api-stripprefix.stripprefix.prefixes=/api
        - traefik.http.services.twir-api.loadbalancer.server.port=3002
        - traefik.docker.network=traefik-public
      update_config:
        parallelism: 2
      restart_policy:
        condition: any
        delay: 30s
        max_attempts: 30
      endpoint_mode: dnsrr
      mode: replicated
      replicas: 1

  bots:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: bots
    image: registry.satont.ru/twir/bots:latest
    secrets:
      - twir_doppler_token
    networks:
      - twir
    deploy:
      restart_policy:
        condition: any
        delay: 30s
        max_attempts: 30
      endpoint_mode: dnsrr

  parser:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: parser
    image: registry.satont.ru/twir/parser:latest
    secrets:
      - twir_doppler_token
    deploy:
      update_config:
        parallelism: 2
      restart_policy:
        condition: any
        delay: 30s
        max_attempts: 30
      mode: replicated
      replicas: 6
      endpoint_mode: dnsrr
    networks:
      - twir

  timers:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: timers
    image: registry.satont.ru/twir/timers:latest
    secrets:
      - twir_doppler_token
    networks:
      - twir
    deploy:
      restart_policy:
        condition: any
        delay: 30s
        max_attempts: 30
      endpoint_mode: dnsrr

  scheduler:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: scheduler
    image: registry.satont.ru/twir/scheduler:latest
    secrets:
      - twir_doppler_token
    networks:
      - twir
    deploy:
      restart_policy:
        condition: any
        delay: 30s
        max_attempts: 30
      endpoint_mode: dnsrr

  eventsub:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: eventsub
    image: registry.satont.ru/twir/eventsub:latest
    secrets:
      - twir_doppler_token
    networks:
      - twir
      - traefik-public
    deploy:
      restart_policy:
        condition: any
        delay: 30s
        max_attempts: 30
      endpoint_mode: dnsrr
      labels:
        - traefik.enable=true
        - traefik.http.routers.twir-eventsub.rule=Host(`eventsub.twir.app`)
        - traefik.http.services.twir-eventsub.loadbalancer.server.port=3003
        - traefik.docker.network=traefik-public

  eval:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: eval
    image: registry.satont.ru/twir/eval:latest
    secrets:
      - twir_doppler_token
    deploy:
      update_config:
        parallelism: 2
      mode: replicated
      replicas: 4
      endpoint_mode: dnsrr
      restart_policy:
        condition: any
        delay: 30s
        max_attempts: 30
    networks:
      - twir

  integrations:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: integrations
    image: registry.satont.ru/twir/integrations:latest
    secrets:
      - twir_doppler_token
    networks:
      - twir
    deploy:
      restart_policy:
        condition: any
        delay: 30s
        max_attempts: 30
      endpoint_mode: dnsrr

  landing:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: landing
    image: registry.satont.ru/twir/landing:latest
    secrets:
      - twir_doppler_token
    networks:
      - twir
      - traefik-public
    deploy:
      restart_policy:
        condition: any
        delay: 30s
        max_attempts: 30
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      labels:
        - traefik.enable=true
        - traefik.http.routers.twir-landing.rule=Host(`twir.app`)
        - traefik.http.routers.twir-landing.middlewares=cloudflarewarp
        - traefik.http.services.twir-landing.loadbalancer.server.port=3000
        - traefik.docker.network=traefik-public

  dashboard:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dashboard
    image: registry.satont.ru/twir/dashboard:latest
    secrets:
      - twir_doppler_token
    networks:
      - twir
      - traefik-public
    deploy:
      restart_policy:
        condition: any
        delay: 30s
        max_attempts: 30
      endpoint_mode: dnsrr
      labels:
        - traefik.enable=true
        - traefik.http.routers.twir-dashboard.rule=Host(`twir.app`) && PathPrefix(`/dashboard`)
        - traefik.http.routers.twir-dashboard.middlewares=dashboard-stripprefix
        - traefik.http.middlewares.dashboard-stripprefix.stripprefix.prefixes=/dashboard
        - traefik.http.services.twir-dashboard.loadbalancer.server.port=80
        - traefik.docker.network=traefik-public

  public:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: public
    image: registry.satont.ru/twir/public:latest
    secrets:
      - twir_doppler_token
    networks:
      - twir
      - traefik-public
    deploy:
      restart_policy:
        condition: any
        delay: 30s
        max_attempts: 30
      endpoint_mode: dnsrr
      labels:
        - traefik.enable=true
        - traefik.http.routers.twir-public.rule=Host(`twir.app`) && PathPrefix(`/p`)
        - traefik.http.routers.twir-public.middlewares=public-stripprefix
        - traefik.http.middlewares.public-stripprefix.stripprefix.prefixes=/p
        - traefik.http.services.twir-public.loadbalancer.server.port=80
        - traefik.docker.network=traefik-public

  overlays:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: overlays
    image: registry.satont.ru/twir/overlays:latest
    networks:
      - twir
      - traefik-public
    deploy:
      restart_policy:
        condition: any
        delay: 30s
        max_attempts: 30
      endpoint_mode: dnsrr
      labels:
        - traefik.enable=true
        - traefik.http.routers.twir-overlays.rule=Host(`twir.app`) && PathPrefix(`/overlays`)
        - traefik.http.routers.twir-overlays.middlewares=overlays-stripprefix
        - traefik.http.middlewares.overlays-stripprefix.stripprefix.prefixes=/overlays
        - traefik.http.services.twir-overlays.loadbalancer.server.port=80
        - traefik.docker.network=traefik-public

  websockets:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: websockets
    image: registry.satont.ru/twir/websockets:latest
    secrets:
      - twir_doppler_token
    networks:
      - twir
      - traefik-public
    deploy:
      restart_policy:
        condition: any
        delay: 30s
        max_attempts: 30
      endpoint_mode: dnsrr
      labels:
        - traefik.enable=true
        - traefik.http.routers.twir-websockets.rule=Host(`twir.app`) && PathPrefix(`/socket`)
        - traefik.http.routers.twir-websockets.middlewares=sockets-stripprefix
        - traefik.http.middlewares.sockets-stripprefix.stripprefix.prefixes=/socket
        - traefik.http.services.twir-websockets.loadbalancer.server.port=3004
        - traefik.docker.network=traefik-public

  tokens:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: tokens
    image: registry.satont.ru/twir/tokens:latest
    secrets:
      - twir_doppler_token
    networks:
      - twir
    deploy:
      update_config:
        parallelism: 2
      mode: replicated
      replicas: 4
      restart_policy:
        condition: any
        delay: 30s
        max_attempts: 30
      endpoint_mode: dnsrr

  emotes-cacher:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: emotes-cacher
    image: registry.satont.ru/twir/emotes-cacher:latest
    secrets:
      - twir_doppler_token
    networks:
      - twir
    deploy:
      update_config:
        parallelism: 2
      restart_policy:
        condition: any
        delay: 30s
        max_attempts: 30
      endpoint_mode: dnsrr
      mode: replicated
      replicas: 4

  events:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: events
    image: registry.satont.ru/twir/events:latest
    secrets:
      - twir_doppler_token
    networks:
      - twir
    deploy:
      update_config:
        parallelism: 2
      restart_policy:
        condition: any
        delay: 30s
        max_attempts: 30
      endpoint_mode: dnsrr
      mode: replicated
      replicas: 6

  ytsr:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: ytsr
    image: registry.satont.ru/twir/ytsr:latest
    secrets:
      - twir_doppler_token
    networks:
      - twir
    deploy:
      update_config:
        parallelism: 2
      restart_policy:
        condition: any
        delay: 30s
        max_attempts: 30
      endpoint_mode: dnsrr
      mode: replicated
      replicas: 6

  tts:
    image: aculeasis/rhvoice-rest
    networks:
      - twir
    deploy:
      update_config:
        parallelism: 2
      restart_policy:
        condition: any
        delay: 30s
        max_attempts: 30
      endpoint_mode: dnsrr
      mode: replicated
      replicas: 4

  discord:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: discord
    image: registry.satont.ru/twir/discord:latest
    secrets:
      - twir_doppler_token
    networks:
      - twir
    deploy:
      restart_policy:
        condition: any
        delay: 30s
        max_attempts: 30
      endpoint_mode: dnsrr

volumes:
  postgres-data:
  redis-data:
  minio-data:


networks:
  twir:
    name: twir
    external: true
  traefik-public:
    external: true

secrets:
  twir_doppler_token:
    external: true
  twir_postgres_user:
    external: true
  twir_postgres_db:
    external: true
  twir_postgres_password:
    external: true
