version: "3.7"

services:
  postgres:
    restart: unless-stopped
    image: postgres:14-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: tsuwari
      POSTGRES_PASSWORD: tsuwari
      POSTGRES_DB: tsuwari
  
  redis:
    restart: unless-stopped
    image: eqalpha/keydb
    volumes:
      - ./keydb_data:/data

  api:
    restart: unless-stopped
    image: satont/tsuwari:api
    env_file:
      - .env
    deploy:
      replicas: 2
    ports:
      - 3002:3002

  bots:
    restart: unless-stopped
    image: satont/tsuwari:bots
    env_file:
      - .env

  scheduler:
    restart: unless-stopped
    image: satont/tsuwari:scheduler
    env_file:
      - .env

  streamstatus:
    restart: unless-stopped
    image: satont/tsuwari:streamstatus
    env_file:
      - .env
      
  watched:
    restart: unless-stopped
    image: satont/tsuwari:watched
    env_file:
      - .env