version: '3.7'

services:
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8085:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=pgpool:5432
      - ADMINER_PLUGINS=enum-types enum-option json-column
    networks:
      - tsuwari-dev

  #  https://www.pgpool.net/mediawiki/index.php/Main_Page
  pgpool:
    image: bitnami/pgpool:4
    ports:
      - "54321:5432"
    environment:
      - PGPOOL_BACKEND_NODES=0:postgres:5432
      - PGPOOL_ENABLE_LDAP=no
      - PGPOOL_POSTGRES_USERNAME=tsuwari
      - PGPOOL_POSTGRES_PASSWORD=tsuwari
      - PGPOOL_SR_CHECK_USER=tsuwari
      - PGPOOL_SR_CHECK_PASSWORD=tsuwari
      - PGPOOL_ADMIN_USERNAME=pgpool
      - PGPOOL_ADMIN_PASSWORD=pgpool
    healthcheck:
      test: [ "CMD", "/opt/bitnami/scripts/pgpool/healthcheck.sh" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - tsuwari-dev

  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: tsuwari
      POSTGRES_PASSWORD: tsuwari
      POSTGRES_DB: tsuwari
    networks:
      - tsuwari-dev

  redis:
    image: redis/redis-stack:latest
    restart: always
    ports:
      - "6385:6379"
    volumes:
      - redis-data:/data
    networks:
      - tsuwari-dev

  language-detector:
    image: ghcr.io/twirapp/language-detector:latest
    restart: always
    ports:
      - "3012:3012"
    environment:
      - APP_ENV=development

  tts:
    image: aculeasis/rhvoice-rest
    restart: always
    ports:
      - "7001:8080"
    networks:
      - tsuwari-dev

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9090"
    restart: "always"
    ports:
      - "8000:9000"
      - "8090:9090"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio-password
    volumes:
      - minio-data:/data

  temporal:
    image: temporalio/auto-setup:1.22.2
    restart: always
    depends_on:
      - postgres
    environment:
      - DB=postgresql
      - DB_PORT=5432
      # this is db addr
      - POSTGRES_SEEDS=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=tsuwari
      - POSTGRES_PWD=tsuwari
      - POSTGRES_DB=temporal
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
    volumes:
      - ./configs/temporal:/etc/temporal/config/dynamicconfig
    networks:
      - tsuwari-dev
    ports:
      - "7233:7233"
    labels:
      kompose.volume.type: configMap

  temporal-admin-tools:
    image: temporalio/admin-tools:1.22.2
    restart: always
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    networks:
      - tsuwari-dev
    stdin_open: true
    tty: true

  temporal-ui:
    image: temporalio/ui:2.21.0
    restart: always
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    networks:
      - tsuwari-dev
    ports:
      - "7234:8080"

volumes:
  redis-data:
  postgres-data:
  minio-data:

networks:
  tsuwari-dev:
    driver: bridge
