version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: api
  bots:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: bots
  dota:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dota
  eval:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: eval
  eventsub:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: eventsub
  integrations:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: integrations
  parser:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: parser
  scheduler:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: scheduler
  streamstatus:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: streamstatus
  timers:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: timers
  migrations:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: migrations
