version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    image: registry.satont.dev/tsuwari/api
  bots:
    build:
      context: .
      dockerfile: ./apps/bots/Dockerfile
    image: registry.satont.dev/tsuwari/bots
  dota:
    build:
      context: .
      dockerfile: ./apps/dota/Dockerfile
    image: registry.satont.dev/tsuwari/dota
  eval:
    build:
      context: .
      dockerfile: ./apps/eval/Dockerfile
    image: registry.satont.dev/tsuwari/eval
  eventsub:
    build:
      context: .
      dockerfile: ./apps/eventsub/Dockerfile
    image: registry.satont.dev/tsuwari/eventsub
  integrations:
    build:
      context: .
      dockerfile: ./apps/integrations/Dockerfile
    image: registry.satont.dev/tsuwari/integrations
  parser:
    build:
      context: .
      dockerfile: ./apps/parser/Dockerfile
    image: registry.satont.dev/tsuwari/parser
  scheduler:
    build:
      context: .
      dockerfile: ./apps/scheduler/Dockerfile
    image: registry.satont.dev/tsuwari/scheduler
  streamstatus:
    build:
      context: .
      dockerfile: ./apps/streamstatus/Dockerfile
    image: registry.satont.dev/tsuwari/streamstatus
  timers:
    build:
      context: .
      dockerfile: ./apps/timers/Dockerfile
    image: registry.satont.dev/tsuwari/timers
  migrations:
    build:
      context: .
      dockerfile: ./libs/typeorm/Dockerfile
    image: registry.satont.dev/tsuwari/migrations
