version: '3.7'

services:
  tsuwari:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        GO_VERSION: "1.21.0"
        NODE_VERSION: "18"
        PNPM_VERSION: "8"
    command: sleep infinity
    user: tsuwari
    volumes:
      - .:/workspace:cached
    ports:
      - "3005:3005"
    depends_on:
      - postgres
      - redis
    networks:
      - tsuwari-dev
    links:
      - postgres
      - redis
      - adminer

  adminer:
    image: adminer
    restart: always
    ports:
      - "8085:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=postgres:5432
      - ADMINER_PLUGINS=enum-types enum-option json-column
    networks:
      - tsuwari-dev

  postgres:
    restart: unless-stopped
    image: postgres:14-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: tsuwari
      POSTGRES_PASSWORD: tsuwari
      POSTGRES_DB: tsuwari
    networks:
      - tsuwari-dev
    ports:
      - "54321:5432"

  redis:
    restart: unless-stopped
    image: redis/redis-stack:latest
    ports:
      - "6385:6379"
    volumes:
      - redis-data:/data
    networks:
      - tsuwari-dev

  tts:
    restart: unless-stopped
    image: aculeasis/rhvoice-rest
    ports:
      - "7001:8080"
    networks:
      - tsuwari-dev

  landing:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: landing

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9090"
    restart: "always"
    ports:
      - "8000:9000"
      - "8090:9090"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio-password
    volumes:
      - minio-data:/data

volumes:
  redis-data:
  postgres-data:
  minio-data:

networks:
  tsuwari-dev:
    driver: bridge
