version: '3.7'

services:
  tsuwari:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        GO_VERSION: "1.20.1"
        NODE_VERSION: "18.12.1"
        PNPM_VERSION: "8"
    command: sleep infinity
    user: tsuwari
    volumes:
      - .:/workspace:cached
    ports:
        - "3005:3005"
    depends_on:
        - postgres
        - redis
    networks:
      - tsuwari-dev
    links:
      - postgres
      - redis
      - adminer
      
  selenium-hub:
    image: selenium/hub
    environment:
      - SE_SESSION_REQUEST_TIMEOUT=30
      - SE_NODE_SESSION_TIMEOUT=10
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
  selenium-node:
    image: selenium/node-chrome
    shm_size: 1gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_SESSION_TIMEOUT=10
      - SE_NODE_MAX_SESSIONS=4

  adminer:
    image: adminer
    restart: always
    ports:
      - "8085:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=postgres:5432
      - ADMINER_PLUGINS=enum-types enum-option json-column
    networks:
      - tsuwari-dev

  postgres:
    restart: unless-stopped
    image: postgres:14-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: tsuwari
      POSTGRES_PASSWORD: tsuwari
      POSTGRES_DB: tsuwari
    networks:
      - tsuwari-dev
    ports:
      - "54321:5432"

  redis:
    restart: unless-stopped
    image: redis/redis-stack:latest
    ports:
      - "6385:6379"
    volumes:
      - redis-data:/data
    networks:
      - tsuwari-dev

  tts:
    restart: unless-stopped
    image: aculeasis/rhvoice-rest:amd64
    ports:
      - "7000:8080"
    networks:
      - tsuwari-dev

volumes:
  redis-data:
  postgres-data:

networks:
  tsuwari-dev:
    driver: bridge
