version: '3.7'

services:
  backend:
    user: 1000:1000
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    volumes:
      - ./:/app
    networks:
      - tsuwari_dev
    depends_on:
      - postgres
      - nats
      - minio
      - redis
    ports:
      - 3005:3005

  postgres:
    restart: unless-stopped
    image: postgres:14-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    #command: postgres -c 'max_connections=100000'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - tsuwari_dev
    ports:
      - 5432:5432

  minio:
    image: quay.io/minio/minio
    command: server --address 0.0.0.0:9000 --console-address ":9001" /data
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
      MINIO_REGION_NAME: eu-east-1
      MINIO_SERVER_URL: https://minio.tsuwari.tk

    healthcheck:
      test:
        [
          'CMD',
          'curl',
          '-f',
          'http://localhost:9000/minio/health/live'
        ]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - tsuwari_dev

  redis:
    restart: unless-stopped
    image: redis/redis-stack:latest
    volumes:
      - redis-data:/data
    networks:
      - tsuwari_dev

  nats:
    restart: unless-stopped
    image: nats:latest
    networks:
      - tsuwari_dev

networks:
  tsuwari_dev:
    name: tsuwari_dev

volumes:
  postgres-data: null
  redis-data: null
  nats-data: null
  minio-data: null
  pnpm: null
  node_modules: null
