version: '3.7'

services:
  tsuwari:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        GO_VERSION: "2:1.19.3"
        NODE_VERSION: "18.12.1"
        PNPM_VERSION: "7.17.1"
    command: sleep infinity
    user: tsuwari
    volumes:
      - .:/workspace:cached
    ports:
        - 3005:3005
    depends_on:
        - postgres
        - redis
    networks:
      - tsuwari-dev
    links: 
      - postgres
      - redis
      - adminer

  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080
    environment:
      - ADMINER_DEFAULT_SERVER=postgres:5432
      - ADMINER_PLUGINS=enum-types enum-option json-column
    networks:
      - tsuwari-dev

  postgres:
    restart: unless-stopped
    image: postgres:14-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: tsuwari
      POSTGRES_PASSWORD: tsuwari
      POSTGRES_DB: tsuwari
    networks:
      - tsuwari-dev

  redis:
    restart: unless-stopped
    image: redis/redis-stack:latest
    volumes:
      - redis-data:/data
    networks:
      - tsuwari-dev

volumes:
  redis-data:
  postgres-data:

networks:
  tsuwari-dev:
    driver: bridge