packages:
  - 'apps/*'
  - 'libs/*'
  - 'frontend/*'
  - web

catalog:
  typescript: 5.7.3
  vue: 3.5.12
  vite: 5.4.6
  vue-tsc: 2.1.10
  '@vueuse/core': 11.2.0
  '@vueuse/components': 11.2.0
  naive-ui: 2.38.0
