version: '3'

includes:
  parser:
    taskfile: ./apps/parser/Taskfile.yml
    dir: ./apps/parser
  timers:
    taskfile: ./apps/timers/Taskfile.yml
    dir: ./apps/timers

tasks:
  build-libs:
    cmds:
      - pnpm turbo run build --filter=./libs/*

  migrations:
    cmds:
      - doppler run -- pnpm run --filter=@tsuwari/typeorm setup

  dev-node:
    cmds:
      - doppler run -- pnpm dev

  prepare:
    cmds:
      - task: build-libs
      - task: migrations

  dev:
    deps: [prepare]
    cmds:
      - task: parser:dev
      - task: timers:dev
      - task: dev-node
