version: '3'

includes:
  parser:
    taskfile: ./apps/parser/Taskfile.yml
    dir: ./apps/parser
  timers:
    taskfile: ./apps/timers/Taskfile.yml
    dir: ./apps/timers
  api:
    taskfile: ./apps/api/Taskfile.yml
    dir: ./apps/api
  bots:
    taskfile: ./apps/bots/Taskfile.yml
    dir: ./apps/bots

tasks:
  build-libs:
    cmds:
      - pnpm run build:libs

  gen-tokens:
    cmds:
      - pnpm ts-node --esm --transpileOnly tools/tokens.ts

  migrations:
    cmds:
      - doppler run -- pnpm run --filter=@tsuwari/typeorm setup

  prepare:
    run: once
    cmds:
      - task: build-libs
      - task: migrations

  parser-dev:
    deps: [prepare]
    cmds:
      - task: parser:dev

  timers-dev:
    deps: [prepare]
    cmds:
      - task: timers:dev

  api-dev:
    deps: [prepare]
    cmds:
      - task: api:dev

  bots-dev:
    deps: [prepare]
    cmds:
      - task: bots:dev

  node-dev:
    deps: [prepare]
    cmds:
      - pnpm dev

  dev:
    deps: [parser-dev, timers-dev, api-dev, bots-dev, node-dev]

  docker-local-build:
    cmds:
      - docker compose -f docker-compose.build.yml build --progress=plain
