version: '3'

includes:
  parser:
    taskfile: ./apps/parser/Taskfile.yml
    dir: ./apps/parser
  timers:
    taskfile: ./apps/timers/Taskfile.yml
    dir: ./apps/timers
  api:
    taskfile: ./apps/api/Taskfile.yml
    dir: ./apps/api
  bots:
    taskfile: ./apps/bots/Taskfile.yml
    dir: ./apps/bots
  watched:
    taskfile: ./apps/watched/Taskfile.yml
    dir: ./apps/watched
  tokens:
    taskfile: ./apps/tokens/Taskfile.yml
    dir: ./apps/tokens
  emotes-cacher:
    taskfile: ./apps/emotes-cacher/Taskfile.yml
    dir: ./apps/emotes-cacher
  events:
    taskfile: ./apps/events/Taskfile.yml
    dir: ./apps/events
  scheduler:
    taskfile: ./apps/scheduler/Taskfile.yml
    dir: ./apps/scheduler


tasks:
  build-libs:
    cmds:
      - pnpm run build:libs

  gen-tokens:
    cmds:
      - pnpm ts-node --esm --transpileOnly tools/tokens.ts

  migrations:
    cmds:
      - pnpm run --filter=@tsuwari/typeorm setup

  prepare:
    run: once
    cmds:
      - task: build-libs
      - task: migrations

  parser-dev:
    deps: [prepare]
    cmds:
      - task: parser:dev

  timers-dev:
    deps: [prepare]
    cmds:
      - task: timers:dev

  api-dev:
    deps: [prepare]
    cmds:
      - task: api:dev

  bots-dev:
    deps: [prepare]
    cmds:
      - task: bots:dev

  watched-dev:
    deps: [prepare]
    cmds:
      - task: watched:dev

  tokens-dev:
    deps: [ prepare ]
    cmds:
      - task: tokens:dev

  emotes-cacher-dev:
    deps: [ prepare ]
    cmds:
      - task: emotes-cacher:dev

  events-dev:
    deps: [ prepare ]
    cmds:
      - task: events:dev

  scheduler-dev:
    deps: [ prepare ]
    cmds:
      - task: scheduler:dev

  node-dev:
    deps: [prepare]
    cmds:
      - pnpm dev

  dev:
    deps: [
      tokens-dev,
      parser-dev,
      timers-dev,
      api-dev,
      bots-dev,
      watched-dev,
      emotes-cacher-dev,
      events-dev,
      scheduler-dev,
      node-dev
    ]

  docker-local-build:
    cmds:
      - docker compose -f docker-compose.build.yml build --progress=plain
