version: '3'

tasks:
  dev:
    cmds:
      - reflex -s -r '\.go$' go run cmd/main.go

  build:
    cmds:
      - rm main || true
      - go build cmd/main.go

  debug:
    cmds:
      - go build -gcflags=all="-N -l" ./cmd/main.go
      - ./main
