version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    parameters:
      target:
        type: string
    steps:
      - checkout
      - run:
          name: Build application Docker image
          command: |
            docker build --target << parameters.target >> --tag twir-base:<< parameters.target >> .


workflows:
  all-tests:
    jobs:
      - build:
          matrix:
            parameters:
              target:
                - builder
                - node_prod_base
                - go_prod_base
