version: 2.1

jobs:
  base:
    docker:
      - image: cimg/base:stable
    parameters:
      target:
        type: string
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            docker build -f base.Dockerfile --target << parameters.target >> --tag twir-base:<< parameters.target >> .
  backend:
    description: Build backend image for << parameters.target >>
    docker:
      - image: cimg/base:stable
    parameters:
      target:
        type: string
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            docker build -f ./apps/<< parameters.target >>/Dockerfile --tag twir:<< parameters.target >> .


workflows:
  build-base-images:
    jobs:
      - base:
          matrix:
            parameters:
              target:
                - builder
                - node_prod_base
                - go_prod_base
      - backend:
          requires:
            - base
          name: build-backend
          matrix:
            parameters:
              target:
                - api
                - bots
                - discord
                - emotes-cacher
                - eval
                - events
                - eventsub
                - integrations
                - language-detector
                - parser
                - scheduler
                - timers
                - tokens
                - websockets
                - ytsr
