name: Docker v2

on:
  push:

jobs:
  base:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - builder
          - node_prod_base
          - go_prod_base
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build ${{ matrix.target }}
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          file: ./base.Dockerfile
          target: ${{ matrix.target }}
          tags: twir-base:${{ matrix.target }}
          outputs: type=docker,dest=/tmp/twir-base:${{ matrix.target }}.tar
