name: Docker v2

on:
  push:

jobs:
  base:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - builder
          - node_prod_base
          - go_prod_base
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build ${{ matrix.target }}
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          file: ./base.Dockerfile
          target: ${{ matrix.target }}
          tags: twir-base:${{ matrix.target }}
          outputs: type=docker,dest=/tmp/twir-base:${{ matrix.target }}.tar
      - name: Upload ${{ matrix.target }} artifact
        uses: actions/upload-artifact@v3
        with:
          name: "twir-base:${{ matrix.target }}"
          path: "/tmp/twir-base_${{ matrix.target }}.tar"
          retention-days: 1

  backend:
    runs-on: ubuntu-latest
    needs:
      - base
    strategy:
      matrix:
        target:
          - api
          - bots
          - discord
          - emotes-cacher
          - eval
          - events
          - eventsub
          - integrations
          - language-detector
          - parser
          - scheduler
          - timers
          - tokens
          - websockets
          - ytsr
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Load builder image
        uses: actions/download-artifact@v3
        with:
          name: "twir-base:builder"
          path: /tmp/twir-base_builder.tar

      - name: Load node_prod_base image
        uses: actions/download-artifact@v3
        with:
          name: "twir-base:node_prod_base"
          path: /tmp/twir-base_node_prod_base.tar

      - name: Load go_prod_base image
        uses: actions/download-artifact@v3
        with:
          name: "twir-base:go_prod_base"
          path: /tmp/twir-base_go_prod_base.tar

      - name: Build ${{ matrix.target }}
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          file: ./apps/${{ matrix.target }}/Dockerfile
          tags: twir:${{ matrix.target }}
