name: Docker v2

on:
  push:

jobs:
  base:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - builder
          - node_prod_base
          - go_prod_base
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build ${{ matrix.target }}
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          file: ./base.Dockerfile
          target: ${{ matrix.target }}
          load: true
          tags: twir-base:${{ matrix.target }}
          outputs: type=docker,dest=/tmp/${{ matrix.target }}.tar
          cache-from: type=gha,scope=twir-base:${{ matrix.target }}
          cache-to: type=gha,mode=max,scope=twir-base:${{ matrix.target }}
      - name: Upload ${{ matrix.target }} artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}
          path: /tmp/${{ matrix.target }}.tar
          retention-days: 1

  backend:
    runs-on: ubuntu-latest
    needs:
      - base
    strategy:
      matrix:
        target:
          - api
          - bots
          - discord
          - emotes-cacher
          - eval
          - events
          - eventsub
          - integrations
          - language-detector
          - parser
          - scheduler
          - timers
          - tokens
          - websockets
          - ytsr
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Restore base images
        uses: actions/download-artifact@v3
        with:
          path: /tmp

      - name: Load base images
        run: |
          docker load --input /tmp/go_prod_base/builder.tar &
          docker load --input /tmp/node_prod_base/node_prod_base.tar &
          docker load --input /tmp/node_prod_base/go_prod_base.tar &
          wait
          docker image ls

      - name: Build ${{ matrix.target }}
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: true
          file: ./apps/${{ matrix.target }}/Dockerfile
          tags: twir:${{ matrix.target }}
          cache-from: type=gha,scope=twir:${{ matrix.target }}
          cache-to: type=gha,mode=max,scope=twir:${{ matrix.target }}
