name: Renovate
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:
  push:

jobs:
  renovate:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v32.118.0
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.GH_PERSONAL_TOKEN }}