name: Renovate

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  renovate:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v32.153.0
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.GH_PERSONAL_TOKEN }}